import { Injectable, Inject } from '@nestjs/common';
import { LoggerService } from '../../../core/logger/logger.service';
import { IVoucherRepository } from '../interfaces/voucher.interfaces';
import {
  VOUCHER_REPOSITORY,
  TALLY_SYNC_QUEUE,
  VOUCHER_STATUS,
} from '../constants/voucher.constants';
import { VoucherBuilderEngine } from '../services/voucher-builder.engine';
import { IQueueService } from '../../../infrastructure/queue/queue.interfaces';
import { QUEUE_PROVIDER } from '../../../infrastructure/queue/queue.constants';

@Injectable()
export class ProcessVoucherBuilderUseCase {
  constructor(
    @Inject(VOUCHER_REPOSITORY) private readonly repository: IVoucherRepository,
    private readonly builderEngine: VoucherBuilderEngine,
    @Inject(QUEUE_PROVIDER) private readonly queue: IQueueService,
    private readonly logger: LoggerService,
  ) {}

  async execute(feeAllocationCandidateId: string): Promise<void> {
    const startTime = Date.now();
    this.logger.debug(
      `Building voucher for allocation ${feeAllocationCandidateId}`,
      'ProcessVoucherBuilderUseCase',
    );

    // MOCK: Fetch allocation, payment candidate, and student
    // In reality, inject repositories from fee-validation, payment-parser, student domains.
    const mockAllocationData = {
      allocatedAmount: 8000,
      allocationBreakdown: [{ feeHeadName: 'Tuition', allocated: 8000 }],
    };
    const mockPaymentData = { gateway: 'razorpay', transactionId: 'TX123' };
    const mockStudent = { id: 'stu_1', admissionNumber: 'ADM-2026-001' };

    let buildResult;

    try {
      buildResult = await this.builderEngine.buildReceiptVoucher(
        mockAllocationData,
        mockPaymentData,
        mockStudent,
      );
    } catch (error) {
      this.logger.error(
        `Failed to build voucher`,
        (error as Error).stack,
        'ProcessVoucherBuilderUseCase',
      );
      throw error;
    }

    const candidateData = {
      voucherType: buildResult.voucherType,
      voucherNumber: buildResult.voucherNumber,
      studentId: mockStudent.id,
      feeAllocationCandidateId,
      totalDebit: buildResult.totalDebit,
      totalCredit: buildResult.totalCredit,
      validationStatus: buildResult.status,
      warnings: buildResult.warnings,
      manualReviewRequired: buildResult.status === VOUCHER_STATUS.MANUAL_REVIEW,
      lines: buildResult.lines.map((l) => ({
        voucherLedgerId: l.ledgerId,
        type: l.type,
        amount: l.amount,
        description: l.description,
      })),
      references: buildResult.references.map((r) => ({
        referenceType: r.type,
        referenceValue: r.value,
      })),
      narrations: buildResult.narrations.map((n) => ({
        content: n,
        isAutoGenerated: true,
      })),
    };

    const logData = {
      level: 'INFO',
      message: 'Voucher validation executed',
      details: { executionTimeMs: Date.now() - startTime } as any,
    };

    const savedCandidate = await this.repository.saveVoucherResult(candidateData, logData);

    if (buildResult.status === VOUCHER_STATUS.VALIDATED) {
      await this.queue.addJob(TALLY_SYNC_QUEUE, 'sync-tally', {
        voucherCandidateId: savedCandidate.id,
      });
      // In real implementation, update candidate status to READY_FOR_SYNC after queueing
    }
  }
}
