import { Injectable, Inject } from '@nestjs/common';
import { LoggerService } from '../../../core/logger/logger.service';
import { IVoucherRepository } from '../interfaces/voucher.interfaces';
import {
  VOUCHER_REPOSITORY,
  TALLY_SYNC_QUEUE,
  VOUCHER_STATUS,
} from '../constants/voucher.constants';
import { VoucherBuilderEngine } from '../services/voucher-builder.engine';
import { IQueueService } from '../../../infrastructure/queue/queue.interfaces';
import { QUEUE_PROVIDER } from '../../../infrastructure/queue/queue.constants';

@Injectable()
export class ProcessVoucherBuilderUseCase {
  constructor(
    @Inject(VOUCHER_REPOSITORY) private readonly repository: IVoucherRepository,
    private readonly builderEngine: VoucherBuilderEngine,
    @Inject(QUEUE_PROVIDER) private readonly queue: IQueueService,
    private readonly logger: LoggerService,
  ) {}

  async execute(payload: any): Promise<void> {
    const startTime = Date.now();
    const candidateId = payload.candidateId || payload.feeAllocationCandidateId;
    this.logger.debug(
      `Building voucher for candidate ${candidateId}`,
      'ProcessVoucherBuilderUseCase',
    );

    const companyId = payload.companyId;
    const companyExists = await this.repository.checkCompanyExists(companyId);
    if (!companyExists) {
      throw new Error(`Company ${companyId} not found`);
    }

    // If it's the old payload from Student Fee (which only sent feeAllocationCandidateId and companyId),
    // we need to adapt it. If it's the new Generic Payload, we use it directly.
    let buildPayload = payload;

    if (!payload.voucherType && payload.feeAllocationCandidateId) {
      const candidate = await this.repository.findFeeAllocationCandidateById(
        payload.feeAllocationCandidateId,
      );
      if (!candidate || !candidate.studentPaymentCandidate) {
        throw new Error(
          `Fee allocation candidate ${payload.feeAllocationCandidateId} not found or missing payment candidate`,
        );
      }
      buildPayload = {
        voucherType: 'RECEIPT',
        candidateId: payload.feeAllocationCandidateId,
        companyId,
        allocationData: {
          allocatedAmount:
            Number(candidate.studentPaymentCandidate.amount) || 0,
          allocationBreakdown: [
            {
              feeHeadName: 'Fee Collection',
              allocated: Number(candidate.studentPaymentCandidate.amount) || 0,
            },
          ],
        },
        paymentData: {
          gateway:
            candidate.studentPaymentCandidate.paymentGateway || '',
          transactionId:
            candidate.studentPaymentCandidate.paymentCandidateId || '',
          amount: Number(candidate.studentPaymentCandidate.amount) || 0,
        },
        student: {
          id: candidate.studentPaymentCandidate.studentId,
          admissionNumber: candidate.studentPaymentCandidate.admissionNumber,
        },
      };
    }

    let buildResult;

    try {
      buildResult = await this.builderEngine.build(buildPayload);
    } catch (error: any) {
      this.logger.error(
        `Failed to build voucher`,
        (error as Error).stack,
        'ProcessVoucherBuilderUseCase',
      );
      throw error;
    }

    // Resolve voucherDate: use invoice date from payload, fall back to today
    const voucherDate = buildPayload.invoice?.date
      ? new Date(buildPayload.invoice.date)
      : new Date();

    const candidateData = {
      voucherType: buildResult.voucherType,
      voucherNumber: buildResult.voucherNumber,
      date: voucherDate,
      studentId: buildPayload.student?.id || null,
      feeAllocationCandidateId:
        buildPayload.voucherType === 'RECEIPT'
          ? buildPayload.candidateId
          : null,
      batchSyncItemId: buildPayload.batchSyncItemId,
      companyId: buildPayload.companyId,
      totalDebit: buildResult.totalDebit,
      totalCredit: buildResult.totalCredit,
      validationStatus: buildResult.status,
      warnings: buildResult.warnings,
      manualReviewRequired: buildResult.status === VOUCHER_STATUS.MANUAL_REVIEW,
      lines: buildResult.lines.map((l) => ({
        voucherLedgerId: l.ledgerId,
        ledgerName: l.ledgerName,
        type: l.type,
        amount: l.amount,
        description: l.description,
      })),
      references: buildResult.references.map((r) => ({
        referenceType: r.type,
        referenceValue: r.value,
      })),
      narrations: buildResult.narrations.map((n) => ({
        content: n,
        isAutoGenerated: true,
      })),
    };

    const logData = {
      level: 'INFO',
      message: 'Voucher validation executed',
      details: { executionTimeMs: Date.now() - startTime } as any,
    };

    const savedCandidate = await this.repository.saveVoucherResult(
      candidateData,
      logData,
    );

    if (buildResult.status === VOUCHER_STATUS.VALIDATED) {
      await this.queue.addJob(TALLY_SYNC_QUEUE, 'sync-tally', {
        voucherCandidateId: savedCandidate.id,
      });
      // In real implementation, update candidate status to READY_FOR_SYNC after queueing
    }
  }
}
