export enum VmmsMatchReason {
  GSTIN_MISSING = 'GSTIN_MISSING',
  GSTIN_INVALID = 'GSTIN_INVALID',
  NO_VENDOR_BRANCH = 'NO_VENDOR_BRANCH',
  MULTIPLE_LEDGERS = 'MULTIPLE_LEDGERS',
  LEDGER_NOT_FOUND = 'LEDGER_NOT_FOUND',
  SUCCESS = 'SUCCESS',
}
