export const MATCHING_REPOSITORY = 'MATCHING_REPOSITORY';
export const STUDENT_MATCHING_QUEUE = 'student-matching';
export const FEE_VALIDATION_QUEUE = 'fee-validation';

export const MATCH_RESULT_STATUS = {
  MATCHED: 'MATCHED',
  MULTIPLE_MATCHES: 'MULTIPLE_MATCHES',
  NO_MATCH: 'NO_MATCH',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
};
