export const VALIDATION_REPOSITORY = 'VALIDATION_REPOSITORY';
export const FEE_VALIDATION_QUEUE = 'fee-validation';
export const VOUCHER_GENERATION_QUEUE = 'voucher-generation';

export const VALIDATION_RESULT_STATUS = {
  VALID: 'VALID',
  PARTIALLY_ALLOCATED: 'PARTIALLY_ALLOCATED',
  ADVANCE_PAYMENT: 'ADVANCE_PAYMENT',
  OVERPAYMENT: 'OVERPAYMENT',
  DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',
  INVALID: 'INVALID',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
};
